Adiciona AuthModal completo e ajustes no login/cadastro
:\Users\andre\OneDrive\Área de Trabalho\conexao-mente-digital-main>git
pull origin main --rebase
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 139 (delta 12), reused 139 (delta 12), pack-reused 0 (from
0)
Receiving objects: 100% (139/139), 2.54 MiB | 10.67 MiB/s, done.
Resolving deltas: 100% (12/12), done.
From https://github.com/tyconde/conexao-mente-digital
 * branch            main       -> FETCH_HEAD
  * [new branch]      main       -> origin/main
  Auto-merging index.html
  CONFLICT (add/add): Merge conflict in index.html
  Auto-merging package-lock.json
  CONFLICT (add/add): Merge conflict in package-lock.json
  Auto-merging src/components/AuthModal.tsx
  CONFLICT (add/add): Merge conflict in src/components/AuthModal.tsx
  Auto-merging src/components/Navigation.tsx
  CONFLICT (add/add): Merge conflict in src/components/Navigation.tsx
  error: could not apply f237304... Adiciona AuthModal completo e
  ajustes no login/cadastro
  hint: Resolve all conflicts manually, mark them as resolved with
  hint: "git add/rm <conflicted_files>", then run "git rebase
  --continue".
  hint: You can instead skip this commit: run "git rebase --skip".
  hint: To abort and get back to the state before "git rebase", run "git
  rebase --abort".
  Adiciona AuthModal completo e ajustes no login/cadastro

  # Conflicts:
  #       index.html
  #       package-lock.json
  #       src/components/AuthModal.tsx
  #       src/components/Navigation.tsx

  # Please enter the commit message for your changes. Lines starting
  # with '#' will be ignored, and an empty message aborts the commit.
  #
  .git/COMMIT_EDITMSG [unix] (20:58 15/09/2025)
  2,0-1 Top"~/OneDrive/Área de
  Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG" [unix] 23L,
  7  #se enter the commit message for your changes. Lines starting
    # with '#' will be ignored, and an empty message aborts the commit.
      #
        .git/COMMIT_EDITMSG [unix] (20:58 15/09/2025)
	  2,0-1 Top"~/OneDrive/Área de
	    Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
	    [unix] 23L,
	      720B
	      .git/COMMIT_EDITMSG[+] [unix] (21:17 15/09/2025)
	      66,6 Botrecording @a  # Please enter the commit message
	      for your changes. Lines starting
	        # with '#' will be ignored, and an empty message aborts
		the commit.
		  #
		    .git/COMMIT_EDITMSG [unix] (20:58 15/09/2025)
		      2,0-1 Top"~/OneDrive/Área de
		        Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
			[unix] 23L,
			  720B
			  .git/COMMIT_EDITMSG[+] [unix] (21:17
			  15/09/2025)
			  66,6 Botrecording @a  # Please enter the
			  commit message for your changes. Lines
			  starting
			    # with '#' will be ignored, and an empty
			    message aborts the commit.
			      #
			        .git/COMMIT_EDITMSG [unix] (20:58
				15/09/2025)
				  2,0-1 Top"~/OneDrive/Área de
				    Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
				    [unix] 23L,
				      720B
				      .git/COMMIT_EDITMSG[+] [unix]
				      (21:17 15/09/2025)
				      66,6 Botrecording @a  # Please
				      enter the commit message for your
				      changes. Lines starting
				        # with '#' will be ignored, and
					an empty message aborts the
					commit.
					  #
					    .git/COMMIT_EDITMSG [unix]
					    (20:58 15/09/2025)
					      2,0-1 Top"~/OneDrive/Área
					      de
					        Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
						[unix] 23L,
						  720B
						  .git/COMMIT_EDITMSG[+]
						  [unix] (21:17
						  15/09/2025)
						  66,6 Botrecording @a
						  # Please enter the
						  commit message for
						  your changes. Lines
						  starting
						    # with '#' will be
						    ignored, and an
						    empty message aborts
						    the commit.
						      #
						        .git/COMMIT_EDITMSG
							[unix] (20:58
							15/09/2025)
							  2,0-1
							  Top"~/OneDrive/Área
							  de
							    Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
							    [unix] 23L,
							      720B
							      .git/COMMIT_EDITMSG[+]
							      [unix]
							      (21:17
							      15/09/2025)
							      66,6
							      Botrecording
							      @a  #
							      P  #se enter the commit message for your changes. Lines starting
							        # with
								'#' will
								be
								ignored,
								and an
								empty
								message
								aborts
								the
								commit.
								  #
								    .git/COMMIT_EDITMSG
								    [unix]
								    (20:58
								    15/09/2025)
								      2,0-1
								      Top"~/OneDrive/Área
								      de
								        Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
									[unix]
									23L,
									  720B
									  .git/COMMIT_EDITMSG[+]
									  [unix]
									  (21:17
									  15/09/2025)
									  66,6
									  Botrecording
									  @aPlease enter the commit message for your changes. Lines starting
  # with '#' will be ignored, and an empty message aborts the commit.
  #
  .git/COMMIT_EDITMSG [unix] (20:58 15/09/2025)
  2,0-1 Top"~/OneDrive/Área de
  Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG" [unix] 23L,
  720B
.git/COMMIT_EDITMSG[+] [unix] (21:17 15/09/2025)                                                                                                               66,6 Botrecording @alease
							      enter the
							      commit
							      message
							      for your
							      changes.
							      Lines
							      starting
							        # with
								'#' will
								be
								ignored,
								and an
								empty
								message
								aborts
								the
								commit.
								  #
								    .git/COMMIT_EDITMSG
								    [unix]
								    (20:58
								    15/09/2025)
								      2,0-1
								      Top"~/OneDrive/Área
								      de
								        Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG"
									[unix]
									23L,
									  720B
									  .git/COMMIT_EDITMSG[+]
									  [unix]
									  (21:17
									  15/09/2025)
									  66,6
									  Botrecording
							Please enter the commit message for your changes. Lines starting
  # with '#' will be ignored, and an empty message aborts the commit.
  #
  .git/COMMIT_EDITMSG [unix] (20:58 15/09/2025)
  2,0-1 Top"~/OneDrive/Área de
  Trabalho/conexao-mente-digital-main/.git/COMMIT_EDITMSG" [unix] 23L,
  720B
.git/COMMIT_EDITMSG[+] [unix] (21:17 15/09/2025)                                                                                                               66,6 Botrecording @a20B